name: Terraform Apply

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "infra/**"
      - "lambda/**"

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    env:
      AWS_REGION: ${{ vars.AWS_REGION || 'us-east-1' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Lambda dependencies
        run: |
          cd lambda/csv-to-json
          npm ci
          cd ../presign-upload
          npm ci

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Plan
        working-directory: infra
        run: terraform plan -out tfplan

      - name: Terraform Apply
        working-directory: infra
        run: terraform apply -auto-approve tfplan
